什么是服务器
 服务器可以是专业的服务器，也可以是个人电脑
 能在特定的（IP）服务器的特定端口上监听客户的请求 并根据请求的路径 返回相应的结果都叫服务器
 IP：就想门牌号（在北京上网：地址就是北京的ip，在上海上网，ip地址就是上海的）
 端口：一个服务器可以有多个端口

什么是客户端
    只要能向特定（IP）服务器的特定端口发起请求并接受相应的的都叫客户端
数据在服务器和客户端之间传递
    可以把服务器硬盘上 已经有的静态文件 发送给客户端
    也可以由服务器经过逻辑处理生成动态内容 返回给客户端 比如当前时间
一个http事物有一条（从客户端发往服务器的）请求命令和一个（服务器返回客户端的）响应结果组成

形形色色的能够进行通信 我们就需要指明一种协议（http https）和一种数据封装格式html json


（2）在git 访问 服务器端口
    curl -v http://localhost:12345

（3）域名解析
     先找浏览器缓存chrome://net-internals/#dns

     浏览器缓存--本电脑host -- dns系统 --运营商Dns --找根域 --com域

favicon.ico图标
